name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  macos:
    timeout-minutes: 15
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build tests
        run: |
          cmake -DNODEC_WORLD_BUILD_TESTS=ON -B ./build
          cmake --build ./build
      - name: Run tests
        working-directory: build
        run: |
          ctest -C Debug --output-on-failure
